name: ETL integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run integration tests
        env:
          API_URL: ${{ secrets.API_URL }}
          TOKEN_PROSPECTIVO_2023: ${{ secrets.TOKEN_PROSPECTIVO_2023 }}
          TOKEN_PROSPECTIVO_2022: ${{ secrets.TOKEN_PROSPECTIVO_2022 }}
          TOKEN_RETROSPECTIVO: ${{ secrets.TOKEN_RETROSPECTIVO }}
          TOKEN_JAV: ${{ secrets.TOKEN_JAV }}
          TOKEN_ADMIN: ${{ secrets.TOKEN_ADMIN }}
        run: |
          pytest tests/
